website/posts/urls.py
# URL mappings for the posts app.

from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("tos", views.tos, name="tos"),
    path("create", views.create, name="create"),
    path("view/<int:post_id>", views.view, name="view"),
    path("comment/<int:post_id>", views.comment, name="comment"),
    path("comment/delete/<int:comment_id>/<int:post_id>", views.delete_comment, name="delete_comment"),
    path("edit/<int:post_id>", views.edit, name="edit"),
    path("user/<int:user_id>", views.view_user, name="view_user"),
    path("user/<str:username>", views.view_user_by_username, name="view_user_by_username"),
    path("login", views.login_view, name="login_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("reset_password", views.reset_password, name="reset_password"),
]

website/posts/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    """
        The database model representing an individual post. These make up the bulk of the app's
        content.
    """
    title = models.CharField(max_length=100, blank=False)
    body = models.TextField(max_length=25000, blank=False)
    pub_date = models.DateTimeField("Published on")
    # The author field should be linked to the user object that created it.
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    # The "string representation" for the admin interface will be the post's title.
    def __str__(self):
        return self.title.title()

class Comment(models.Model):
    """
        A Comment is, in essence, a reply to a Post (tied to an authenticated user).
    """
    # Associate the comment with an existing post.
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # The author field should be linked to the user object that created it.
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    body = models.TextField(max_length=1000, blank=False)
    pub_date = models.DateTimeField("Published on")
    # The string representation should include the post's title and the username associated with it.
    def __str__(self):
        return "Reply to " + self.post.title.title() + " by " + self.author.username

website/posts/forms.py
from django import forms

class PasswordResetForm(forms.Form):
	password1 = forms.CharField(label="Enter your new password here (255 characters maximum)", max_length=255,required=True,widget=forms.PasswordInput)
	password2 = forms.CharField(label="Password (confirm)", max_length=255, required=True,widget=forms.PasswordInput)

class CreatePostForm(forms.Form):
	title = forms.CharField(label="Title (100 characters maximum)",max_length=100,required=True)
	message = forms.CharField(label="Enter your message here (25,000 characters maximum)",max_length=25000,required=True,widget=forms.Textarea)

class CommentForm(forms.Form):
	message = forms.CharField(label="Enter your comment here (1,000 characters maximum)", max_length=1000, required=True,widget=forms.Textarea)

class LoginForm(forms.Form):
	username = forms.CharField(label="Username", max_length=150, required=True)
	password = forms.CharField(label="Password", max_length=255, required=True,widget=forms.PasswordInput)

website/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, get_user_model, logout

from .models import Post, Comment
from .forms import PasswordResetForm, CreatePostForm, CommentForm, LoginForm

import markdown as md

def index(request):
	"""
		Display a list of the latest 10 posts, sorted by date in descending order.
	"""
	posts = Post.objects.order_by("-pub_date")
	# Display 10 posts per page.
	paginator = Paginator(posts, 10)
	page_number = request.GET.get("page")
	page_obj = paginator.get_page(page_number)
	return render(request, "posts/index.html", {"page_obj": page_obj})

def about(request):
    """
        Display an "about" page with a brief description of the site.
    """
    return render(request, "posts/about.html")

def tos(request):
    """
        Display the privacy policy and terms of service.
    """
    return render(request,"posts/tos.html")

def create(request):
	"""
		Display the form for creating a new post. If a new post has been received, store
		it in the database and display a message to the user upon a successful save.
	"""
	if (request.method == "POST"):
		form = CreatePostForm(request.POST)
		# This action should only be available to active, authenticated accounts.
		if (not request.user.is_authenticated or not request.user.is_active):
			messages.error(request,"You must be signed in to create posts!")
			return redirect("posts:login_view")
		# Check that the user has the appropriate permissions!
		if (not request.user.has_perm("posts.add_post")):
			messages.error(request,"You do not have permission to post messages!")
			return redirect("posts:index")
		# If the test cookie is successfully set, clean it up. Otherwise, we cannot proceed!
		if request.session.test_cookie_worked():
			request.session.delete_test_cookie()
			# Set a session variable for the user's per-session post count.
			request.session['num_posts'] = request.session.get('num_posts', 0)
		else:
			messages.error(request, "You must have cookies enabled to post. Please check your browser settings and try again!")
			request.session.set_test_cookie()
			return render(request, "posts/create.html", {"form":form})
		# Limit the user to 100 posts per session.
		if request.session['num_posts'] >= 100:
			messages.error(request, "You have posted too many times (100) during this session! Please try again later.")
			request.session.set_test_cookie()
			return render(request, "posts/create.html", {"form":form})
		# Validate the provided form data before proceeding.
		if (form.is_valid()):
			title = form.cleaned_data['title']
			body = md.markdown(form.cleaned_data['message'])
			author = request.user
			pub_date = timezone.now()
			post = Post.objects.create(title=title,body=body,pub_date=pub_date,author=author)
			post.save()
			# Increment the user's per-session post count.
			request.session['num_posts'] += 1 
			messages.success(request, "Your post was saved successfully!")
			return redirect("posts:index")
		else:
			messages.error(request,"There was a problem saving your post. Please check your input and try again!")
			request.session.set_test_cookie()
			return render(request, "posts/create.html", {"form":form})
	else:
		# Create an instance of the form to pass to our template.
		form = CreatePostForm()
		request.session.set_test_cookie()
		# This action should only be available to active, authenticated accounts.
		if (not request.user.is_authenticated or not request.user.is_active):
			messages.error(request,"You must be signed in to create posts!")
			return redirect("posts:login_view")
		# Check that the user has the appropriate permissions!
		if (not request.user.has_perm("posts.add_post")):
			messages.error(request,"You do not have permission to post messages!")
			return redirect("posts:index")
		# Display the form.
		return render(request, "posts/create.html", {"form":form})

def view(request,post_id):
	"""
		View the full contents of an individual post.
	"""
	post = get_object_or_404(Post,pk=post_id)
	# Sort the comments in ascending order.
	comments = Comment.objects.filter(post__id=post_id).order_by("pub_date")
	# Count the total number of comments for this post.
	comment_count = Comment.objects.filter(post__id=post_id).count()
	# Display 100 comments per page.
	paginator = Paginator(comments,100)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	context = {
		"post":post,
		"page_obj":page_obj,
		"comment_count":comment_count,
	}
	return render(request,"posts/view.html",context)

def comment(request, post_id):
    """
        Display the form for commenting on a specific post. If a new comment has
        been received, process it and store it in the database.
    """
    # First, find the post that we're commenting on!
    post = get_object_or_404(Post,pk=post_id) 
    if (request.method == "POST"):
        # Create an instance of the appropriate form.
        form = CommentForm(request.POST)
        context = {
            "post_id":post_id,
            "post":post,
            "form":form,
        }
        # Only authenticated users with the appropriate permission can post comments!
        if (not request.user.is_active or not request.user.is_authenticated): 
            messages.error(request, "You must be signed in to post comments!")
            return redirect("posts:login_view")
        if (not request.user.has_perm("posts.add_comment")):
            messages.error(request, "You do not have permission to post comments!")
            return redirect("posts:index")
        # If the test cookie is successfully set, clean it up. Otherwise, we cannot proceed!
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            # Set a session variable for the user's per-session comment count.
            request.session['num_comments'] = request.session.get('num_comments', 0)
        else:
            messages.error(request, "You must have cookies enabled to post comments. Please check your browser settings and try again!")
            request.session.set_test_cookie()
            return render(request, "posts/comment.html", context)
        # Limit the user to 1000 comments per session.
        if request.session['num_comments'] >= 1000:
            messages.error(request, "You have commented too many times (1000) during this session! Please try again later.")
            request.session.set_test_cookie()
            return render(request, "posts/comment.html", context)
        # Validate the provided form data before proceeding.
        if (form.is_valid()):    
            body = form.cleaned_data['message']
            author = request.user
            pub_date = timezone.now()  
            comment = Comment.objects.create(body=body,pub_date=pub_date,post_id=post_id,author=author)
            comment.save()
            request.session['num_comments'] += 1
            messages.success(request,"Your comment has been saved successfully!")
            return redirect("posts:view", post_id=post_id)
        else:
            messages.error(request, "There was a problem submitting your comment. Please check your input and try again!")
            form = CommentForm()
            return render(request, "posts/comment.html", context)
    else:
        # Only authenticated users with the appropriate permission can post comments!
        if (not request.user.is_active or not request.user.is_authenticated): 
            messages.error(request, "You must be signed in to post comments!")
            return redirect("posts:login_view")
        if (not request.user.has_perm("posts.add_comment")):
            messages.error(request, "You do not have permission to post comments!")
            return redirect("posts:index")
        request.session.set_test_cookie()
        # Display the appropriate form.
        form = CommentForm()
        context = {
            "post_id":post_id,
            "post":post,
            "form":form,
        }
        return render(request, "posts/comment.html", context)
       
def edit(request, post_id):
	"""
		Edit the content of an individual post. Optionally delete or update the content of the post,
		depending upon the button clicked.
	""" 
	# Check to see if the post exists first!
	post = get_object_or_404(Post, pk=post_id)
	if (request.method == "POST"):
		if (request.POST['submit'] == "Delete this post!"):
			# Check to see if the user has permission to delete posts first!
			if (not request.user.is_authenticated or not request.user.is_active):
				messages.error(request,"You must be signed in to delete posts!")
				return redirect("posts:login_view")
			if (not request.user.has_perm("posts.delete_post")):
				messages.error(request,"You do not have permission to delete posts!")
				return redirect("posts:view", post_id=post_id)
			# Posts can only be deleted by their owner!
			if (not request.user == post.author):
				messages.error(request,"You can only delete your own posts!")
				return redirect("posts:view", post_id=post_id)
			post.delete()
			messages.success(request, "Post deleted: " + post.title.title())
			return redirect("posts:index")
		else:
			# Validate the provided form data before proceeding.
			form = CreatePostForm(request.POST)
			if (form.is_valid()):
				# Check to see if the user has permission to change posts first!
				if (not request.user.is_authenticated or not request.user.is_active):
					messages.error(request,"You must be signed in to edit posts!")
					return redirect("posts:login_view")
				if (not request.user.has_perm("posts.delete_post")):
					messages.error(request,"You do not have permission to edit posts!")
					return redirect("posts:view", post_id=post_id)
				# Posts can only be changed by their owner!
				if (not request.user == post.author):

website/posts/templates/posts/about.html
{% extends "layout.html" %}
{% block content %}
<h1>About The Site</h1>
<hr>
<p><strong>The Blue Hydrangea</strong> is a platform for creating your own blog or journal! It's based upon a simple 
content management system <strong>(CMS)</strong> which includes some of the following features:</p>
<ul>
	<li><strong>administrators</strong> can create posts using HTML and <a href="https://www.markdownguide.org">Markdown,</a></li>
	<li>a convenient interface for managing accounts and content.</li>
</ul>
<h2>Frequently Asked Questions</h2>
<ul>
    <li><a href="#faq1">How can I get an account here?</a></li>
	<li><a href="#faq2">What can I post about here?</a></li>
</ul>
<h2 id="faq1">How can I get an account here?</h2>
<p>After you have read over the <a href="{% url 'posts:tos' %}">privacy policy and terms of service,</a> please <a href="mailto:sepia.temps-0h@icloud.com">contact me</a> 
    and include the following information in your e-mail:
</p>
<ul>
    <li>your desired username (this should not exceed <strong>150 characters</strong> and be alphanumeric, e.g. Guest1),</li>
    <li>your full name,</li>
    <li>your e-mail address.</li>
</ul>
<p>Your full name and e-mail address will <strong>only</strong> be visible to administrators. This information will <strong>not</strong> be 
    shared without your permission. If your account has been <strong>approved,</strong> you will be contacted with a temporary password which you can then 
    reset to any value of your choosing!
</p>
<h2 id="faq2">What can I post about here?</h2>
<p>
	Within certain limits, you can post and share just about <strong>anything</strong> that you are interested in! Please check the 
	<a href="{% url 'posts:tos' %}">privacy policy and terms of service</a> for more information on what is considered <strong>appropriate.</strong>
</p>
{% endblock %}

website/posts/templates/posts/comment.html
{% extends "layout.html" %}
{% block content %}
    <h1>Comment On: {{ post.title.title }}</h1>
    <hr>
    {% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <p>
        <strong>Note:</strong> Please read the <a href="{% url 'posts:tos' %}">privacy policy and terms of service</a>
        before you proceed. Thanks!
    </p>
    <form action="{% url 'posts:comment' post.id %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <div id="submit_button_container">
            <input type="submit" name="submit" value="Submit your comment!">
        </div>
    </form>
{% endblock %}

website/posts/templates/posts/create.html
{% extends "layout.html" %}
{% block content %}
    <h1>New Post</h1>
    <hr>
    <p>
        <strong>Note:</strong> Please read the <a href="{% url "posts:tos" %}">privacy policy and terms of service</a>
        before you proceed. Thanks!
    </p>
    {% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if request.user.is_authenticated and request.user.is_active and request.user.is_staff %}
    <p><a href="https://www.markdownguide.org/" target="_blank">Markdown</a> is enabled!</p>
    {% endif %}
    <form action="{% url "posts:create" %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <div id="submit_button_container">
            <input type="submit" name="submit" value="Submit your post!">
        </div>
    </form>
{% endblock %}

website/posts/templates/posts/edit.html
{% extends "layout.html" %}
{% block content %}
    <h1>Edit Post: {{ post.title.title }}</h1>
    <hr>
    <p>
        <strong>Note:</strong> Please read the <a href="{% url "posts:tos" %}">privacy policy and terms of service</a>
        before you proceed. Thanks!
    </p>
    {% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if request.user.is_authenticated and request.user.is_active and request.user.is_staff %}
    <p><a href="https://www.markdownguide.org/" target="_blank">Markdown</a> is enabled!</p>
    {% endif %}
    <form action="{% url 'posts:edit' post_id %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <div id="submit_button_container">
            <input type="submit" name="submit" value="Update this post!">
        </div>
        <div id="submit_button_container">
            <input type="submit" name="submit" value="Delete this post!">
        </div>
    </form>
{% endblock %}

website/posts/templates/posts/index.html
{% extends "layout.html" %}
{% block content %}
    {% if request.user.is_authenticated and request.user.is_active and perms.posts.add_post %}
    <h1>{% now "l, F jS, Y" %} <a href="{% url 'posts:create' %}">(New Post)</a></h1>
    {% else %}
    <h1>{% now "l, F jS, Y" %}</h1>
    {% endif %}
    <hr>
    {% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% for post in page_obj %}
    <article>
    <h2><a href="{% url 'posts:view' post_id=post.id %}">{{ post.title.title }}</a></h2>
    {% if post.author.is_staff %}
    {{ post.body|safe|truncatechars_html:500 }}
    {% else %}
    {{ post.body|linebreaksbr|truncatechars_html:500 }}
    {% endif %}
    <p>Last updated <strong>{{ post.pub_date }}</strong> by <a href="{% url 'posts:view_user_by_username' post.author.username %}">{{ post.author.username }}</a>
    </article>
    <br>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; First</a>
                <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
    
            <span class="current">
                Page <strong>{{ page_obj.number }}</strong> of <strong>{{ page_obj.paginator.num_pages }}</strong>
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

website/posts/templates/posts/login.html
{% extends "layout.html" %}
{% block content %}
<h1>Login</h1>
<hr>
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<p><strong>Forgotten your password?</strong> Contact me <a href="mailto:sepia.temps-0h@icloud.com">here</a> for 
assistance!</p>
<form action="{% url 'posts:login_view' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <div id="submit_button_container">
        <input type="submit" name="submit" value="Login!">
    </div>
</form>
{% endblock %}

website/posts/templates/posts/reset_password.html
{% extends "layout.html" %}
{% block content %}
<h1>Reset Password</h1>
<hr>
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<p>You can use the form below to reset your password. You will be <strong>signed out</strong> if the change
is successful, so make note of your new password <strong>before</strong> proceeding!</p>
<form action="{% url 'posts:reset_password' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <div id="submit_button_container">
        <input type="submit" name="submit" value="Change my password!">
    </div>
</form>
{% endblock %}

website/posts/templates/posts/tos.html
{% extends "layout.html" %}
{% block content %}
<h1>Privacy/Terms of Service</h1>
<hr>
<h2 id="top">Table of Contents</h2>
<ul>
    <li><a href="#priv_policy">Privacy Policy</a></li>
    <li><a href="#tos">Terms of Service</a></li>
</ul>
<h3 id="priv_policy">Privacy Policy</h2>
<p><strong>The Blue Hydrangea</strong> has been designed to collect a <strong>minimum</strong> amount of data in order
    to operate. Our web server software logs the following information when you visit:</p>
<ul>
    <li>the IP address from which the request originated,</li>
    <li>the URL requested,</li>
    <li>the web browser used to visit the site (as well as its version),</li>
    <li>the link which referred you to the site.</li>
</ul>
<p>In addition, the following storage areas provided by your browser <strong>may</strong>
be used to temporarily store information related to your session:</p>
<ul>
    <li>cookies,</li>
    <li>local storage,</li>
    <li>session storage.</li>
</ul>
<p><strong>None</strong> of these bits of information are used to track your activity across any 
other website. They are strictly used to store information related to your account and session,
e.g. whether or not you are an authenticated user.</p>
<h3 id="tos">Terms of Service</h2>
<p><strong>The Blue Hydrangea</strong> is dedicated to providing a professional, safe environment for
    online discussions. The following guidelines <strong>must</strong> be followed if you intend to post
    or comment on the site:</p>
<ul>
    <li>do not use abusive or hateful language,</li>
    <li>do not post content which is considered illegal (e.g. links to piracy sites),</li>
    <li>do not attempt to interfere with site operation, impersonate staff members or access portions of the 
        site that are restricted to moderators or staff members,</li>
    <li>do not use the site for advertising of <strong>any</strong> kind (exceptions <em>may</em> be made for 
    charitable organizations or fundraisers).</li>
</ul>
<p>Any content or user that fails to adhere to these guidelines will be immediately and <strong>permanently</strong> removed!
</p>
{% endblock %}

website/posts/templates/posts/view.html
{% extends "layout.html" %}
{% block content %}
    {% if request.user.is_authenticated and request.user.is_active and perms.posts.change_post and request.user == post.author %}
    <h1>{{ post.title.title }} <a href="{% url 'posts:edit' post.id %}">(Edit Post)</a></h1> 
    <hr>
    {% else %}
    <h2>{{ post.title.title }}</h2>
    <hr>
    {% endif %}
    {% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if post.author.is_staff %}
    {{ post.body|safe }}
    {% else %}
    {{ post.body|linebreaksbr }}
    {% endif %}
    <p>Last updated <strong>{{ post.pub_date }}</strong> by <a href="{% url 'posts:view_user_by_username' post.author.username %}">{{ post.author.username }}</a> 
        {% if request.user.is_authenticated and request.user.is_active and perms.posts.add_comment %}
        <a href="{% url 'posts:comment' post.id %}">(Comment)</a>
        {% endif %}
    </p>
    <p><strong>Note:</strong> Comments are the responsibility of their owners and do <strong>not</strong> necessarily reflect the views of the site's administrators.</p>
	<h2 id="comments">Comments ({{ comment_count }}):</h2>
        {% for comment in page_obj %}
        <p>
            {{ comment.body|linebreaksbr }}
        </p>
        <p>Posted on <strong>{{ comment.pub_date }}</strong> by <a href="{% url 'posts:view_user_by_username' comment.author.username %}">{{ comment.author.username }}</a>
        {% if request.user.is_authenticated and request.user.is_active and perms.posts.delete_comment %}
        <a href="{% url 'posts:delete_comment' comment.id post.id %}">(Delete Comment)</a>
        {% endif %}
        </p>
        <br>
        {% endfor %}
	<div class="pagination">
        	<span class="step-links">
            		{% if page_obj.has_previous %}
              		<a href="?page=1">&laquo; First</a>
	        	<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                	{% endif %}
                	<span class="current">
                	Page <strong>{{ page_obj.number }}</strong> of <strong>{{ page_obj.paginator.num_pages }}</strong>
    	        	</span>
                	{% if page_obj.has_next %}
                	<a href="?page={{ page_obj.next_page_number }}">Next</a>
                	<a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
    	        	{% endif %}
        	</span>
    	</div>
{% endblock %}

website/posts/templates/posts/view_user.html
{% extends "layout.html" %}
{% block content %}
    <h1>Profile: {{ user.username }}</h1>
    <hr>
    {% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if request.user.is_authenticated and request.user.is_active and perms.auth.view_user %}
    <p>Name: <strong>{{ user.first_name.capitalize }} {{ user.last_name.capitalize }}</strong></p>
    <p>E-mail address: <a href="mailto:{{ user.email }}" target="_blank">{{ user.email }}</a></p>
    <p>Account status: 
        {% if user.is_active %}
        <strong>Active.</strong>
        {% else %}
        <strong>Inactive.</strong>
        {% endif %}
    </p>
    {% endif %}
    <p>Last signed in: <strong>{{ user.last_login }}</strong></p>
    <p>Total posts: <strong>{{ post_count }}</strong></p>
    <p>Total comments: <strong>{{ comment_count }}</strong></p>
    {% if request.user.is_authenticated and request.user.is_active and request.user == user %}
    <p>Password: <a href="{% url 'posts:reset_password' %}">Reset my password</a></p>
    {% endif %}
    <p>
        Latest posts:</strong>
        <ul>
            {% for post in posts %}
            <li><a href="{% url 'posts:view' post.id %}">{{ post.title.title }}</a> - Posted on <strong>{{ post.pub_date }}</strong></li>
            {% endfor %}
        </ul>
    </p>
{% endblock %}